# =====
# INSA Lyon, Département Informatique
# TP C++ 3IF :  Héritage et polymorphisme
# Auteur : B3229
# =====

PATHTOROOT=../

include $(PATHTOROOT)Config.mk

TESTFILE=test.sh

all:
	@bash $(TESTFILE) $(PATHTOROOT)$(TARGET)

clean:
	@rm -rf results.txt *.tmp
